# Generated by Django 2.1 on 2018-08-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name': 'Ministry', 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=254, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='location',
            field=models.CharField(max_length=254, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='office',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngov.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngov.Ministry', verbose_name='Ministry'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='office',
            name='website',
            field=models.URLField(verbose_name='website'),
        ),
    ]
