# Generated by Django 2.1 on 2018-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngov', '0002_auto_20180814_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='location_en',
            field=models.CharField(max_length=254, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='location_ne',
            field=models.CharField(max_length=254, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='name_en',
            field=models.CharField(max_length=254, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='name_ne',
            field=models.CharField(max_length=254, null=True, verbose_name='name'),
        ),
    ]
